# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ac3519a739f9b779bc237fef2b11b2912a9ea0e6bc8ed778050aeec460f0f4a1fd6b26afb9ac0fd0ea212ba5e5194db3444941aa2fd2b50388505ffbedffce3

test:
  secret_key_base: dfad1508aba127081d3ba32503963bdc0df82a9f1dc74814449a19f96fa7c84175d1a23b325304f8db9d17ed99d657b20ea2684dd5bf3a22f6984d16780881b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
